SDT-109: Implement Additional Transformers module unit tests
hmcts/civil-sdt pull request #114
Opened 2023-03-07 18:12 UTC by ladamson-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SDT-109

### Change description ###
Increased transformers module unit test coverage

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-03-08 14:39 UTC, markdathornehmcts commented on transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/IndividualRequestConsumerTransformerTest.java
> +        Assertions.assertEquals(IndividualRequestStatus.ACCEPTED.getStatus(), domain.getRequestStatus(),
Please add *Assertions* as an import

2023-03-09 09:59 UTC, markdathornehmcts commented on transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/SubmitQueryTransformerTest.java
> +        final long sdtCustomerId = 123;
Query: shouldn't long be 123L?

2023-03-09 10:00 UTC, markdathornehmcts commented on transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/SubmitQueryTransformerTest.java
> +import uk.gov.moj.sdt.ws._2013.sdt.submitqueryresponseschema.SubmitQueryResponseType;
add Assertions import here...

2023-03-09 10:56 UTC, markdathornehmcts commented on transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/SubmitQueryTransformerTest.java
> +        Assertions.assertEquals(resultCount, jaxb.getResultCount().longValue(), "Result count does not match");
import should reduce Assertions code

2023-03-09 10:58 UTC, markdathornehmcts commented on transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/SubmitQueryConsumerTransformerTest.java
> +import static org.powermock.api.mockito.PowerMockito.when;
Mockito not PowerMock

2023-03-09 11:07 UTC, markdathornehmcts requested changes
A few comments to peruse and resolve.

2023-03-09 13:48 UTC, markdathornehmcts approved these changes
Pending successful build after CVE suppressions.

2023-03-09 14:18 UTC, markdathornehmcts approved these changes
LGTM

2023-03-10 09:16 UTC, kiran-yenigala-hmcts commented on transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/BulkFeedbackTransformerTest.java
> +        c.setAccessible(true);
why reflection is used, can't we use new BulkFeedbackTransformer()

2023-03-10 09:16 UTC, kiran-yenigala-hmcts commented on transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/BulkRequestTransformerTest.java
> +        Constructor<BulkRequestTransformer> c = BulkRequestTransformer.class.getDeclaredConstructor();
plese see comment above

2023-03-10 09:17 UTC, kiran-yenigala-hmcts commented on transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/IndividualRequestConsumerTransformerTest.java
> +        Constructor<IndividualRequestConsumerTransformer> c
please see comment above

2023-03-10 09:30 UTC, kiran-yenigala-hmcts commented on transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/SubmitQueryConsumerTransformerTest.java
> +            = SubmitQueryConsumerTransformer.class.getDeclaredConstructor();
please see above comment

2023-03-10 09:30 UTC, kiran-yenigala-hmcts commented on transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/UpdateItemTransformerTest.java
> +        Constructor<UpdateItemTransformer> c = UpdateItemTransformer.class.getDeclaredConstructor();
please see above comment

2023-03-15 14:40 UTC, hemantt approved these changes

2023-03-15 15:05 UTC, markdathornehmcts approved these changes
LGTM

2023-03-15 15:17 UTC, merged